/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package e_Abhyaas;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Component;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.image.CropImageFilter;
import java.awt.image.FilteredImageSource;
import java.awt.image.ReplicateScaleFilter;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author akash
 */
class ImageRenderer extends DefaultTableCellRenderer {
  
     String[] macImage=new String[ServerSide.connected.length];
 
      JLabel lbl = new JLabel();
      ImageIcon[] icon = new ImageIcon[ServerSide.connected.length];
       Image[] image=new Image[ServerSide.connected.length];
       ImageIcon[] newicon=new ImageIcon[ServerSide.connected.length];// = new ImageIcon[2];
      
      ImageRenderer() {

  for(int j =0;j<ServerSide.connected.length;j++)
  {
  String[] mac=ServerSide.connected[j][0].split(":");
                         int i =0;
                        String  imageName="";
                        for(String concat:mac){
                        imageName +=(concat);
                        i++;
                        if(i==mac.length)
                        {break;}
                        imageName+="-";
                        }

   macImage[j]=imageName+".jpg";
  // System.out.println("   "+ macImage[j]);

          icon[j] = new ImageIcon(("Invigilator\\"+macImage[j]));
          image[j] = icon[j].getImage();
        image[j] = createImage(new FilteredImageSource(image[j].getSource(),
            new ReplicateScaleFilter(100, 100)));
         newicon[j]=new ImageIcon(image[j]);
        
  }

      }

    @Override
      public Component getTableCellRendererComponent(JTable table, Object value,
                                                     boolean isSelected, boolean hasFocus,
                                                        int row, int column) {
        
        lbl.setHorizontalAlignment(CENTER);
        lbl.setText((String)value);
        lbl.setIcon(newicon[row]);

         return lbl;

      
      }
}

public class NewJFrame extends javax.swing.JFrame {

	/**
	 * Creates new form NewJFrame
	 */
	static javax.swing.JTable jTable2;
	DefaultTableModel tm = null;

	public NewJFrame(String[] list1) {
		initComponents();
		jTable2 = jTable1;
		fillTable();
		// jTable1.setDefaultRenderer(String.class, new CustomRenderer());

		// colorIndex("00-26-82-5D-CB-8D");
		colorIndex();
		jButton1.setText("Start");
		jButton1.addActionListener(new java.awt.event.ActionListener() {

			public void actionPerformed(ActionEvent e) {
				// Execute when button is pressed
                                 if(jButton1.getText().equals("Stop"))
                                 {
                                     ClientThread.start="false";
                                     System.out.println("You clicked the "+jButton1.getText()+" button");
                                 }else{
                                 ClientThread.start="true";
                                 System.out.println("You clicked the "+jButton1.getText()+" button");
                                  jButton1.setText("Stop");
                                 }
				}
		});

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jEditorPane2 = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.SystemColor.activeCaption);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N

        jButton1.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jButton1.setText("Start");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        jLabel1.setText("Welcome Invigilator");

        jTable1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setFont(new java.awt.Font("Goudy Old Style", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Photograph", "Students  List"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setRowHeight(29);
        jScrollPane1.setViewportView(jTable1);

        jEditorPane2.setBackground(new java.awt.Color(0, 0, 0));
        jEditorPane2.setEditable(false);
        jEditorPane2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jEditorPane2.setForeground(new java.awt.Color(255, 255, 255));
        jEditorPane2.setText("e-Abhyaas                                      | Designed by Quiz Module Team");
        jEditorPane2.setAutoscrolls(false);
        jScrollPane3.setViewportView(jEditorPane2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addComponent(jScrollPane1)
            .addComponent(jScrollPane3)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void fillTable() {
            jTable1.setRowHeight(100);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(0).setMinWidth(100);
   jTable1.getColumnModel().getColumn(0).setCellRenderer(new ImageRenderer());
   
		tm = (DefaultTableModel) jTable1.getModel();
             
		int rowcount = tm.getRowCount();
		String[] list = new ServerSide().getlist();
                String[] listNames = new ServerSide().getNameslist(); 
              // BufferedImage[] images = loadImages();
                 JLabel[] j;
                 j= new JLabel[list.length];
                   
                
		// jTable1.setForeground(Color.red);
		for (int i = 0; i < list.length; i++) {
                   // ImageIcon icon=new ImageIcon("C:\\Users\\subhash\\Desktop\\kra_1.jpg");
			tm.addRow(new Object[] { " ",listNames[i]});
                       
                        //tm.setValueAt(icon,i, 0);

		} 

	}

	void colorIndex() {
                  
		jTable1.setDefaultRenderer(String.class, new CustomRenderer());
	}
 

        /**
	 * @param args
	 *            the command line arguments
	 */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JEditorPane jEditorPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;

    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables



}

